### ISSUE TITLE
Why show network error？？

### ISSUE THREAD

**Issue by zhilianbi520** [wonderbeyond/HitUP#4]
Why show network error？Other pages display normally。

**Comment by zhilianbi520** [comment]
https://ghapi.huchen.dev/repositories?language=javascript&since=weekly&spoken_language_code=zh 
No 'Access-Control-Allow-Origin' header is present on the requested resource

**Comment by AwadYoo** [comment]
same question

**Comment by liushaoye** [comment]
what should I do? who can tell me? Its a big bug. @AwadYoo @wonderbeyond [https://images.cnblogs.com/cnblogs_com/liuyangfirst/1865018/o_201016182011%E6%88%AA%E5%B1%8F2020-10-17%2002.15.42.png](url)

**Comment by AwadYoo** [comment]
> what should I do? who can tell me? Its a big bug. @AwadYoo @wonderbeyond [https://images.cnblogs.com/cnblogs_com/liuyangfirst/1865018/o_201016182011%E6%88%AA%E5%B1%8F2020-10-17%2002.15.42.png](url)

have no idea

**Comment by wonderbeyond** [comment]
Fixed in 4.11.3, under auditing by chrome web store.

**Comment by zhilianbi520** [comment]
> Fixed in 4.11.3, under auditing by chrome web store.
Thanks～！ @wonderbeyond
