### ISSUE TITLE
No longer on chrome webstore

### ISSUE THREAD

**Issue by xeddmc** [wonderbeyond/HitUP#8]
Not sure if you are aware or not, but the extension is no longer on the webstore. Was this intentional? Only found out when I went to install it on another device and couldn't find it within the search results.

Just a heads up if not!

xedd

**Comment by wonderbeyond** [comment]
@xeddmc Thanks, I just found the extension is in "Taken down" status. The webstore requires me to "certify that your data usage complies with our developer programme policies."

**Comment by xuexiaoao** [comment]
Is the problem solved please?

**Comment by inixue** [comment]
Can't find Chrome extension

**Comment by wonderbeyond** [comment]
@xuexiaoao Sorry I will no longer maintain this app.
